// This file is auto-generated by @hey-api/openapi-ts

export const ErrorDetailSchema = {
    properties: {
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: [
        'detail'
    ],
    title: 'ErrorDetail'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ParseAcceptedSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status',
            default: 'accepted'
        },
        s3_key: {
            type: 'string',
            title: 'S3 Key'
        }
    },
    type: 'object',
    required: [
        's3_key'
    ],
    title: 'ParseAccepted'
} as const;

export const ParseRequestSchema = {
    properties: {
        s3_key: {
            type: 'string',
            title: 'S3 Key'
        },
        webhook_url: {
            type: 'string',
            title: 'Webhook Url'
        },
        webhook_token: {
            type: 'string',
            title: 'Webhook Token'
        },
        lang: {
            type: 'string',
            title: 'Lang',
            default: 'en'
        },
        backend: {
            type: 'string',
            title: 'Backend',
            default: 'pipeline'
        },
        parse_method: {
            type: 'string',
            title: 'Parse Method',
            default: 'auto'
        }
    },
    type: 'object',
    required: [
        's3_key',
        'webhook_url',
        'webhook_token'
    ],
    title: 'ParseRequest'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
