// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ParseAccepted
 */
export type ParseAccepted = {
    /**
     * Status
     */
    status?: string;
    /**
     * S3 Key
     */
    s3_key: string;
};

/**
 * ParseRequest
 */
export type ParseRequest = {
    /**
     * S3 Key
     */
    s3_key: string;
    /**
     * Webhook Url
     */
    webhook_url: string;
    /**
     * Webhook Token
     */
    webhook_token: string;
    /**
     * Lang
     */
    lang?: string;
    /**
     * Backend
     */
    backend?: string;
    /**
     * Parse Method
     */
    parse_method?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ParseParsePostData = {
    body: ParseRequest;
    path?: never;
    query?: never;
    url: '/parse';
};

export type ParseParsePostErrors = {
    /**
     * S3 object not found
     */
    404: ErrorDetail;
    /**
     * Document exceeds size limit
     */
    413: ErrorDetail;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ParseParsePostError = ParseParsePostErrors[keyof ParseParsePostErrors];

export type ParseParsePostResponses = {
    /**
     * Successful Response
     */
    202: ParseAccepted;
};

export type ParseParsePostResponse = ParseParsePostResponses[keyof ParseParsePostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
